# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 1
  - name: Data Viz projects
    url: "#projects"
    weight: 2
  - name: Posts
    url: "post/"
    weight: 3
  - name: SciArt
    url: "sci-art/"
    weight: 4
  - name: Skills
    url: "#skills"
    weight: 5
  - name: Publications
    url: "publication/"
    weight: 6
  - name: CV
    url: '#CV'
    weight: 7
  - name: Contact
    url: "#contact"
    weight: 8
